//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "t_course")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub f_cno: String,
    pub f_name: String,
    pub f_credit: Option<i8>,
    pub f_semester: Option<i8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::t_student::Entity> for Entity {
    fn to() -> RelationDef {
        super::t_sc::Relation::TStudent.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::t_sc::Relation::TCourse.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
