//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "t_student")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub f_sno: String,
    pub f_name: String,
    pub f_sex: Option<String>,
    pub f_age: Option<i8>,
    pub f_dept: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::t_course::Entity> for Entity {
    fn to() -> RelationDef {
        super::t_sc::Relation::TCourse.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::t_sc::Relation::TStudent.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
